### ISSUE TITLE
URI Malformed Error

### ISSUE THREAD

**Issue by Lukada-taiya** [ncosd/food-pantry-app#319] opened 2024-05-19 22:38 UTC
**Describe the bug**
After running the app, I get a URI malformed error on the screen.

**To Reproduce**
I suspect it due to the app been ran on a windows machine but I am not certain. It shows up on vite error overlay as soon as the app is ran.

![Screenshot 2024-05-19 223619](https://github.com/ncosd/food-pantry-app/assets/60792883/06278133-5c4d-4682-a6fb-ffb107faee3d)

**Comment by dherbst** [comment] 2024-05-21 13:04
Thanks @Lukada-taiya.   I think the issue is from an invalid url in either the `.env` file or `config.js`.   I've changed both to valid urls, can you pull them and try again?  You will have to modify your `.env` file since it is not checked in.

**Comment by dherbst** [comment] 2024-05-24 12:42
Let me know if you are able to reproduce this.

**Closed by dherbst** 2024-05-24 12:42 UTC
